version: '3.7'
services:
    databases:
        image: mysql2
        ports:
            - "3306:3306"
        container_name: gameapp-container
        volumes:
            - ./db_data:/var/lib/mysql
            - ./my.cnf:/etc/mysql/conf.d/my.cnf
        restart: always
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - webapi_network

volumes:
    dbdata:

networks:
    webapi_network:
        driver: bridge